export type QueryKind =
  | "view:dashboard"
  | "view:tasks"
  | "view:calendar"
  | "view:roadmap"
  | "view:planning"
  | "view:settings"
  | "view:news-feed"
  | "view:onboarding"
  | "view:goal-plan"
  | "view:goal-breakdown";

export type CommandKind =
  | "command:create-goal"
  | "command:update-goal"
  | "command:delete-goal"
  | "command:create-task"
  | "command:toggle-task"
  | "command:skip-task"
  | "command:delete-task"
  | "command:delete-tasks-for-date"
  | "command:update-task"
  | "command:confirm-pending-task"
  | "command:reject-pending-task"
  | "command:create-pending-task"
  | "command:upsert-reminder"
  | "command:acknowledge-reminder"
  | "command:delete-reminder"
  | "command:delete-reminders-batch"
  | "command:defer-overflow"
  | "command:undo-defer"
  | "command:save-monthly-context"
  | "command:delete-monthly-context"
  | "command:update-settings"
  | "command:complete-onboarding"
  | "command:reset-data"
  | "command:start-chat-stream"
  | "command:send-chat-message"
  | "command:clear-home-chat"
  | "command:confirm-goal-plan"
  | "command:regenerate-goal-plan"
  | "command:reallocate-goal-plan"
  | "command:adaptive-reschedule"
  | "command:adjust-all-overloaded-plans"
  | "command:regenerate-daily-tasks"
  | "command:refresh-daily-plan"
  | "command:confirm-daily-tasks"
  | "command:generate-bonus-task"
  | "command:accept-task-proposal"
  | "command:reschedule-task"
  | "command:snooze-reschedule"
  | "command:dismiss-reschedule"
  | "command:dismiss-nudge"
  | "command:cant-complete-task"
  | "command:add-task-to-plan"
  | "command:set-vacation-mode"
  | "command:expand-plan-week";

export type EventKind =
  | "ai:stream-start"
  | "ai:token-delta"
  | "ai:stream-end"
  | "agent:progress"
  | "view:invalidate"
  | "reminder:triggered"
  | "job:complete"
  | "job:failed"
  | "entity:patch";

export type Kind = QueryKind | CommandKind | EventKind;
